"""initial schema

Revision ID: 2a471eae6aa4
Revises: 
Create Date: 2026-09-09 21:16:51.666478
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '2a471eae6aa4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Nothing else in the project enables these since it moved to a hosted
    # Supabase database (this used to be backend/scripts/init-db.sql, run
    # once against a local container that no longer exists). vector backs
    # the embedding columns below; pg_trgm backs question_log's fuzzy-match
    # index. IF NOT EXISTS makes re-running this harmless.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('issuing_authority', sa.String(length=512), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('awarded_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('winning_bidder', sa.String(length=512), nullable=True),
    sa.Column('bidder_count', sa.Integer(), nullable=True),
    sa.Column('work_category', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('awarded_date', sa.Date(), nullable=True),
    sa.Column('eligibility_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scope_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('minhash_signature', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_historical_tenders_is_synthetic', 'historical_tenders', ['is_synthetic'], unique=False)
    op.create_index('ix_historical_tenders_scope_embedding_hnsw', 'historical_tenders', ['scope_embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'scope_embedding': 'vector_cosine_ops'})
    op.create_index('ix_historical_tenders_work_category', 'historical_tenders', ['work_category'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('issuing_authority', sa.String(length=512), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_category', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('ingest_status', sa.Enum('PENDING', 'PARSING', 'OCR', 'CHUNKING', 'EMBEDDING', 'EXTRACTING', 'COMPLETE', 'FAILED', name='ingest_status'), nullable=False),
    sa.Column('ingest_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number', name='uq_tenders_reference_number')
    )
    op.create_index('ix_tenders_closing_date', 'tenders', ['closing_date'], unique=False)
    op.create_index('ix_tenders_ingest_status', 'tenders', ['ingest_status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'ESTIMATOR', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('recommendation', sa.Enum('BID', 'NO_BID', 'REVIEW', name='recommendation'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('deciding_gate', sa.String(length=128), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('gates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('counterfactuals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ruleset_version', sa.String(length=32), nullable=False),
    sa.Column('company_profile_id', sa.UUID(), nullable=True),
    sa.Column('document_version_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_decisions_score'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_tender_id', 'decisions', ['tender_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('NIT', 'BOQ', 'CONDITIONS', 'DRAWINGS', 'CORRIGENDUM', 'OTHER', name='document_kind'), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_tender_id', 'documents', ['tender_id'], unique=False)
    op.create_table('faq_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('faq_key', sa.String(length=128), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_answerable', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'faq_key', name='uq_faq_answers_tender_key')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('required_ocr', sa.Boolean(), nullable=False),
    sa.Column('parsed_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version', name='uq_document_versions_document_version')
    )
    op.create_index('ix_document_versions_content_hash', 'document_versions', ['content_hash'], unique=False)
    op.create_table('question_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('normalized_question', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('PREDEFINED_FAQ', 'FREE_SEARCH', name='question_source'), nullable=False),
    sa.Column('matched_faq_key', sa.String(length=128), nullable=True),
    sa.Column('answer_id', sa.UUID(), nullable=True),
    sa.Column('was_answerable', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['faq_answers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_log_normalized_question_trgm', 'question_log', ['normalized_question'], unique=False, postgresql_using='gin', postgresql_ops={'normalized_question': 'gin_trgm_ops'})
    op.create_index('ix_question_log_tender_id', 'question_log', ['tender_id'], unique=False)
    op.create_index('ix_question_log_user_id', 'question_log', ['user_id'], unique=False)
    op.create_table('risk_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_findings_decision_id', 'risk_findings', ['decision_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('page_from', sa.Integer(), nullable=False),
    sa.Column('page_to', sa.Integer(), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('section_path', sa.String(length=512), nullable=True),
    sa.Column('is_table', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'ordinal', name='uq_chunks_version_ordinal')
    )
    op.create_index('ix_chunks_content_fts', 'chunks', [sa.literal_column("to_tsvector('english', content)")], unique=False, postgresql_using='gin')
    op.create_index('ix_chunks_content_hash', 'chunks', ['content_hash'], unique=False)
    op.create_index('ix_chunks_embedding_hnsw', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('user_activity_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'VIEW_TENDER', 'ASK_QUESTION', 'DOWNLOAD_DOCUMENT', 'VIEW_DECISION', 'VIEW_FAQ', 'SEARCH', name='activity_action'), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('document_version_id', sa.UUID(), nullable=True),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_activity_log_action', 'user_activity_log', ['action'], unique=False)
    op.create_index('ix_user_activity_log_user_id_created_at', 'user_activity_log', ['user_id', 'created_at'], unique=False)
    op.create_table('extracted_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('corrected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('corrected_by', sa.String(length=256), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_extracted_facts_confidence'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'key', name='uq_extracted_facts_version_key')
    )
    op.create_index('ix_extracted_facts_tender_id', 'extracted_facts', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extracted_facts_tender_id', table_name='extracted_facts')
    op.drop_table('extracted_facts')
    op.drop_index('ix_user_activity_log_user_id_created_at', table_name='user_activity_log')
    op.drop_index('ix_user_activity_log_action', table_name='user_activity_log')
    op.drop_table('user_activity_log')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_chunks_content_hash', table_name='chunks')
    op.drop_index('ix_chunks_content_fts', table_name='chunks', postgresql_using='gin')
    op.drop_table('chunks')
    op.drop_index('ix_risk_findings_decision_id', table_name='risk_findings')
    op.drop_table('risk_findings')
    op.drop_index('ix_question_log_user_id', table_name='question_log')
    op.drop_index('ix_question_log_tender_id', table_name='question_log')
    op.drop_index('ix_question_log_normalized_question_trgm', table_name='question_log', postgresql_using='gin', postgresql_ops={'normalized_question': 'gin_trgm_ops'})
    op.drop_table('question_log')
    op.drop_index('ix_document_versions_content_hash', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_table('faq_answers')
    op.drop_index('ix_documents_tender_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_decisions_tender_id', table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('users')
    op.drop_index('ix_tenders_ingest_status', table_name='tenders')
    op.drop_index('ix_tenders_closing_date', table_name='tenders')
    op.drop_table('tenders')
    op.drop_index('ix_historical_tenders_work_category', table_name='historical_tenders')
    op.drop_index('ix_historical_tenders_scope_embedding_hnsw', table_name='historical_tenders', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'scope_embedding': 'vector_cosine_ops'})
    op.drop_index('ix_historical_tenders_is_synthetic', table_name='historical_tenders')
    op.drop_table('historical_tenders')
    # ### end Alembic commands ###
