"""add tender listing fields

Revision ID: dc1ffcb0aca6
Revises: 2a471eae6aa4
Create Date: 2026-09-09 22:47:24.079653
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dc1ffcb0aca6'
down_revision: str | None = '2a471eae6aa4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('opening_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenders', sa.Column('portal_tender_id', sa.String(length=64), nullable=True))
    op.add_column('tenders', sa.Column('detail_url', sa.Text(), nullable=True))
    op.add_column('tenders', sa.Column('corrigendum_count', sa.Integer(), nullable=False))
    op.add_column('tenders', sa.Column('is_construction', sa.Boolean(), nullable=False))
    op.add_column('tenders', sa.Column('source_listing', sa.String(length=64), nullable=True))
    op.add_column('tenders', sa.Column('archive_key', sa.String(length=1024), nullable=True))
    op.add_column('tenders', sa.Column('archive_url', sa.Text(), nullable=True))
    op.add_column('tenders', sa.Column('archive_stored_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_tenders_is_construction', 'tenders', ['is_construction'], unique=False)
    op.create_index('ix_tenders_work_category', 'tenders', ['work_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenders_work_category', table_name='tenders')
    op.drop_index('ix_tenders_is_construction', table_name='tenders')
    op.drop_column('tenders', 'archive_stored_at')
    op.drop_column('tenders', 'archive_url')
    op.drop_column('tenders', 'archive_key')
    op.drop_column('tenders', 'source_listing')
    op.drop_column('tenders', 'is_construction')
    op.drop_column('tenders', 'corrigendum_count')
    op.drop_column('tenders', 'detail_url')
    op.drop_column('tenders', 'portal_tender_id')
    op.drop_column('tenders', 'opening_date')
    # ### end Alembic commands ###
