"""record page offsets within a chunk

Revision ID: ee8c4a71aaf2
Revises: dc1ffcb0aca6
Create Date: 2026-10-04 22:16:50.992366
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ee8c4a71aaf2'
down_revision: str | None = 'dc1ffcb0aca6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('page_offsets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'page_offsets')
    # ### end Alembic commands ###
